### ISSUE TITLE
Document source of data

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/Insolation.jl#49]
We should properly document and cite included datasets.

@claresinger you added the csv artifact in #34: do you know where it came from? I assume it's related to https://www.aanda.org/articles/aa/abs/2004/46/aa1335/aa1335.html, but I don't see where the dataset is from.

**Comment by claresinger** [comment]
I downloaded the data file from here: http://vo.imcce.fr/insola/earth/online/earth/earth.html This webpage is linked to in the [Laskar et al. 2004](https://doi.org/10.1051/0004-6361:20041335) paper both at the end of Section 1 and the beginning of Section 12. 
I combined files [`INSOLN.LA2004.BTL.ASC`](http://vo.imcce.fr/insola/earth/online/earth/La2004/INSOLN.LA2004.BTL.ASC) and [`INSOLP.LA2004.BTL.ASC`](http://vo.imcce.fr/insola/earth/online/earth/La2004/INSOLP.LA2004.BTL.ASC) into one file.

**Comment by simonbyrne** [comment]
Thank you!
